server:
  port: 8478

spring:
  # \u4E0B\u9762\u4E24\u4E2A\u914D\u7F6E\u53EF\u4EE5\u8BA9\u5230controller\u5C42\u4E4B\u524D\u7684\u8BF7\u6C42\u9519\u8BEF\u90FD\u629B\u5F02\u5E38
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  # \u56FD\u9645\u5316\u8D44\u6E90\u6587\u4EF6\u8BBE\u7F6E
  messages:
    encoding: UTF-8
    basename: i18n/messages
